spring:
  application:
    name: instrument-service

  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml
  datasource:
    url: jdbc:h2:mem:instrument-db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

multitenancy:
  http:
    header-name: X-TenantId
